### ISSUE TITLE
Typos in Sample Bundles make them invalid

### ISSUE THREAD

**Issue by the-kenny** [inferno-framework/inferno-reference-server#145]
- `Bundle.entry[0].resource.id` must match `Bundle.entry[0].request.url` for `PUT`
- `Bundle.entry[].request.url`: Typo `rul` instead of `url` for some entries
- `Bundle.entry[].request.url`: Typo `Obervation` instead of `Observation` for some entries

**Comment by dehall** [comment]
Thanks for reporting this - the bundles have a long history of manual modifications and apparently some typos made it in. We'll review and get those resolved

**Comment by dehall** [comment]
Closing this issue as the mentioned items have been resolved in the latest release. Please let us know if you see anything else
