### ISSUE TITLE
 Bug in US Core 5.0.1 / USCDI v2, SMART App launch 2.0.0 (1.3.08)

### ISSUE THREAD

**Issue by melmawi** [inferno-framework/inferno-reference-server#69]
1.3.08 expects the scopes to have the same order.
standalone_requested_scopes = standalone_received_scopes but the order of the scopes is incorrect, it errors out.

**standalone_requested_scopes** | launch/patient openid fhirUser offline_access patient/Medication.read patient/AllergyIntolerance.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Device.read patient/DiagnosticReport.read patient/DocumentReference.read patient/Encounter.read patient/Goal.read patient/Immunization.read patient/Location.read patient/MedicationRequest.read patient/Observation.read patient/Organization.read patient/Patient.read patient/Practitioner.read patient/Procedure.read patient/Provenance.read patient/PractitionerRole.read
-- | --
**standalone_received_scopes** | launch/patient openid fhirUser patient/Medication.read patient/AllergyIntolerance.read patient/CarePlan.read patient/CareTeam.read patient/Condition.read patient/Device.read patient/DiagnosticReport.read patient/DocumentReference.read patient/Encounter.read patient/Goal.read patient/Immunization.read patient/Location.read patient/MedicationRequest.read patient/Observation.read patient/Organization.read patient/Patient.read patient/Practitioner.read patient/Procedure.read patient/Provenance.read patient/PractitionerRole.read offline_access

**Comment by arscan** [comment]
Hi @melmawi -- order of the scopes shouldn't matter.  Is this a problem with the test (that is, the test fails your server incorrectly for changing scope order when issuing the access token), or a problem with our demonstration reference API located at https://inferno.healthit.gov/reference-server/r4?  If it is a problem with the test I can move it over to the right spot (https://github.com/onc-healthit/onc-certification-g10-test-kit/issues)

**Comment by melmawi** [comment]
It's a problem with the test, please move it to  (https://github.com/onc-healthit/onc-certification-g10-test-kit/issues) or I can create it there.
Thank you so much for your prompt reply
